openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Autoshowroom API'
  description: 'Autoshowroom api'

servers:
  - url: http://localhost:8081/
    description: local server

paths:
  /orders:
    get:
      operationId: listAllOrders
      description: Get all orders information
      responses:
        200:
          description: Successfully get orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultList[Order]'


components:
  schemas:
    ResultList[Order]:
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Order'
