
package com.example.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.4
 * Thu Jan 09 12:56:58 MSK 2020
 * Generated source version: 3.3.4
 */

@XmlRootElement(name = "addOrder", namespace = "http://service.example.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addOrder", namespace = "http://service.example.com/")

public class AddOrder {

    @XmlElement(name = "order")
    private com.example.entity.Order order;

    public com.example.entity.Order getOrder() {
        return this.order;
    }

    public void setOrder(com.example.entity.Order newOrder)  {
        this.order = newOrder;
    }

}

