
package com.example.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.4
 * Thu Jan 09 12:56:57 MSK 2020
 * Generated source version: 3.3.4
 */

@XmlRootElement(name = "getCustomerResponse", namespace = "http://service.example.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCustomerResponse", namespace = "http://service.example.com/")

public class GetCustomerResponse {

    @XmlElement(name = "return")
    private com.example.entity.Customer _return;

    public com.example.entity.Customer getReturn() {
        return this._return;
    }

    public void setReturn(com.example.entity.Customer new_return)  {
        this._return = new_return;
    }

}

