version: '3.3'
services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'RAPtor1234'
    volumes:
      - db_data:/var/lib/postgresql/data

    container_name: db


  server:
    image: autoshowroom:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - hibernate.connection.url=jdbc:postgresql://db/restored
      - spring.datasource.url=jdbc:postgresql://db/restored
      - spring.datasource.username=postgres
      - spring.datasource.password=RAPtor1234
    container_name: autoshowroom

#External to use a volume created outside this compose scope.
#Probably will need to replace this with creating new volume and populating initial db data from app.
volumes:
  db_data:
    external: true
