<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TestSOAPInterfaceService" targetNamespace="http://cxf.apache.org" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cxf.apache.org" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://cxf.apache.org" schemaLocation="MyService_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="getCarById">
    <wsdl:part name="id" type="xsd:long">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getCarByIdResponse">
    <wsdl:part name="return" type="tns:car">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="tesIF">
    <wsdl:operation name="getCarById">
      <wsdl:input name="getCarById" message="tns:getCarById">
    </wsdl:input>
      <wsdl:output name="getCarByIdResponse" message="tns:getCarByIdResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="TestSOAPInterfaceServiceSoapBinding" type="tns:tesIF">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getCarById">
      <soap:operation soapAction="" style="rpc"/>
      <wsdl:input name="getCarById">
        <soap:body use="literal" namespace="http://cxf.apache.org"/>
      </wsdl:input>
      <wsdl:output name="getCarByIdResponse">
        <soap:body use="literal" namespace="http://cxf.apache.org"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TestSOAPInterfaceService">
    <wsdl:port name="tesIFPort" binding="tns:TestSOAPInterfaceServiceSoapBinding">
      <soap:address location="http://localhost:9090/tesIFPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
