
package com.example.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.4
 * Thu Jan 09 12:56:58 MSK 2020
 * Generated source version: 3.3.4
 */

@XmlRootElement(name = "getCustomer", namespace = "http://service.example.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCustomer", namespace = "http://service.example.com/")

public class GetCustomer {

    @XmlElement(name = "id")
    private long id;

    public long getId() {
        return this.id;
    }

    public void setId(long newId)  {
        this.id = newId;
    }

}

